### ISSUE TITLE
CPAN modularization?

### ISSUE THREAD

**Issue by molecules** [FASTAptamer/FASTAptamer#8]
@KhalidKAlam I could modify this so that we could upload it to CPAN and thus make it easy for people to install it using `cpan` or `cpanm`. Doing so could install the fastaptamer utilities into the same directory as their perl executable. We could name it Bio::FASTAptamer so that it is obviously a biologically related distribution.

**Comment by KhalidKAlam** [comment]
@molecules Thanks for the patience. Feel free to adapt FASTAptamer for CPAN. I initially avoided going this route as the software was designed primarily for bench scientists, without a deep knowledge of scripting, to just download from the lab website and start using immediately.

**Comment by molecules** [comment]
I may consider it in the future, but am currently closing this issue as "wontfix" for the moment to get it off my "issues" list. I will reconsider it if anyone else shows interest.
