### ISSUE TITLE
FASTAptamer not accepting Cutadapt trimmed files

### ISSUE THREAD

**Issue by pmitsis** [FASTAptamer/FASTAptamer#9]
Hi,
We are trying to used files that have been trimmed by Cutadapt to remove primer sequences from our potential aptamers in order to run in FASTAptamer.   For some reason or FASTQ file that has been trimmed does not give readable sequence by Fastaptamer count,  These are 2 FASTQ files that were merged ( cat).  We have tried several variations on trimming all yield the same result with FASTApatmer count.  The untrimmed file seems to work fine.  The outputs for the two cases are below.  Thanks for any help you can give.  

Paul

Untrimmed file:
$ ./fastaptamer_count -i /FASTAptamer/0samples/Sample5_Merged.fq -o /FASTAptamer/0samples/Sample5_Merged.fq_count.fastq

1312525 total sequences.  1231134 unique sequences.
Input file: "/FASTAptamer/0samples/Sample5_Merged.fq".
Output file: "/FASTAptamer/0samples/Sample5_Merged.fq_count.fastq".
Execution time: 11 s.

Trimmed file:
$ ./fastaptamer_count -i /FASTAptamer/0samples/Sample5_Merged_Trimmed_Linked_5primeAnd3primeAnchor_noblank.fastq -o /FASTAptamer/0samples/Sample5_Merged_Trimmed_Linked_5primeAnd3primeAnchor_noblank_count.fastq

0 total sequences.  0 unique sequences.
Input file: "/FASTAptamer/0samples/Sample5_Merged_Trimmed_Linked_5primeAnd3primeAnchor_noblank.fastq".
Output file: "/FASTAptamer/0samples/Sample5_Merged_Trimmed_Linked_5primeAnd3primeAnchor_noblank_count.fastq".
Execution time: 20 s.

**Comment by molecules** [comment]
@pmitsis Interesting. Would you please create sample files containing the first 12 lines of each FASTQ file and attach them here so that we can use them for tests?

**Comment by KhalidKAlam** [comment]
@pmitsis 
It looks like there is something happening to where FASTAptamer is not able to recognize the input file. Are you able to copy and paste (with no additional formatting) the first hundred lines or so of the input file that you are having trouble with?

**Comment by JSchnee21** [comment]
Hi Everyone,

I work with Paul, and I believe I just identified the source of the trouble.  Our pre-trimmed file contained only "LF" end of line characters.  But the output from cutadapt (running on Windows) included both "LF" and "CR" at the end of each line.  Using DOS2UNIX in Cygwin, I stripped off the trailing "CR"'s and this seems to have solved the issue.

Sorry to trouble you.  Though it might be nice if in the next release, diagnosis of this issue was more apparent (or automatically managed) (-:

Thank you,
Jonathan

**Comment by KhalidKAlam** [comment]
@pmitsis @JSchnee21 thanks for the observation! We'll definitely keep this in mind to include in an updated users manual in the future. 

We hope you enjoy FASTAptamer and that it speeds up your combinatorial selection characterization!

**Comment by molecules** [comment]
It looks like the FASTQ format officially contains the newlines particular to the operating system. However, any FASTQ parser should be able to read a FASTQ file written with any newline character.

> Because FASTQ files (like FASTA files) are plain text, the new line characters will normally follow the operating system convention. However, as data are shared between machines, any parser should cope with both Unix style new lines (line feed only, ASCII 10) and DOS/Windows style (carriage return and line feed, ASCII 13 then 10).  
(from section "FASTQ DEFINITION" of the article "[The Sanger FASTQ file format for sequences with quality scores, and the Solexa/Illumina FASTQ variants"](https://academic.oup.com/nar/article-lookup/doi/10.1093/nar/gkp1137)).
